### ISSUE TITLE
서버에 SSH를 활성화

### ISSUE THREAD

**Issue by progh2** [progh2/ecker#2]
원격 접속을 위해서

**Comment by givepcode** [comment]
기본 설정의 raspi-config에서 "SSH"의 항목에 "Enable"로 설정해줘야한다.
(초기에는 기본 설정으로 되어있다)

**Comment by givepcode** [comment]
첫번째

![image](https://cloud.githubusercontent.com/assets/11639311/7272339/11f439f8-e925-11e4-8532-ad897e2d5a6e.png)

두번째

![image](https://cloud.githubusercontent.com/assets/11639311/7272341/24797b4c-e925-11e4-94ed-9933a457a7d5.png)

세번째

![image](https://cloud.githubusercontent.com/assets/11639311/7272349/337538d4-e925-11e4-9ca5-c9dc1132b5ee.png)
